name: Test

on: ['push']

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js '18.2.0'
        uses: actions/setup-node@v3
        with:
          node-version: '18.2.0'
      - run: yarn install --frozen-lockfile
#      - run: yarn build
      - run: yarn test
